name: Upload firmware to GitHub Release

on:
  workflow_call:
    inputs:
      version:
        description: Version of the release
        required: true
        type: string

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: files

      - name: Tree
        run: |-
          tree

      - name: Copy files to output
        run: |-
          shopt -s nullglob
          mkdir output
          version="${{ inputs.version }}"
          pushd files
          for device in *; do
            pushd $device
            if [ "$device" != "$version" ]; then
              pushd $version
              output_path="../../../output/"
            else
              output_path="../../output/"
            fi
            cp manifest.json "${output_path}$device.manifest.json"
            for bin in *.{bin,elf}; do
              md5sum $bin | head -c 32 > "${output_path}$bin.md5"
              sha256sum $bin | head -c 64 > "${output_path}$bin.sha256"
              cp $bin "$output_path"
            done
            if [ "$device" != "$version" ]; then
              popd
            fi
            popd
          done
          popd

      - name: Upload files to release
        uses: softprops/action-gh-release@aec2ec56f94eb8180ceec724245f64ef008b89f5 # v2.4.0
        with:
          files: output/*
          tag_name: ${{ inputs.version }}
